#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from agent_broker_v1.config import BROKER_CFG_V1
from agent_broker_v2.config import BROKER_CFG_V2


SKILL_NAME = "agent-broker-user-diagnose"
SKILL_DESCRIPTION = (
    "Use when a repo instruction or tool message explicitly refers "
    f"you to `{SKILL_NAME}` or `SKILL.md` for brokered CLI "
    "troubleshooting."
)
OUTPUT_PATH = REPO_ROOT / "SKILL.md"


def render_allowlist(allowlist: list[str]) -> str:
    if not allowlist:
        return (
            "The current configured allowlist is empty. If a tool appears to work, "
            "it is coming from outside this broker path."
        )

    quoted = ", ".join(f"`{tool}`" for tool in allowlist)
    return (
        "The current configured allowlist from "
        "`agent_broker_v1/config.py` or `agent_broker_v1/config_local.py` is: "
        f"{quoted}."
    )


def render_v2_allowlist(allowlist: list[str]) -> str:
    if not allowlist:
        return (
            "The current configured v2 allowlist is empty. If a streamed tool path appears "
            "to work, it is coming from outside the repo's v2 broker path."
        )

    quoted = ", ".join(f"`{tool}`" for tool in allowlist)
    return (
        "If you are debugging the streamed v2 path, inspect "
        "`agent_broker_v2/config.py` or `agent_broker_v2/config_local.py`. "
        f"The current configured v2 allowlist is: {quoted}."
    )


def render_example_tools(allowlist: list[str]) -> str:
    examples = [tool for tool in allowlist if tool in {"echo", "pwd", "sleep"}]
    if not examples:
        examples = allowlist[:2]
    if not examples:
        return "Start with the simplest currently allowlisted executable before testing a more complex command."
    quoted = " or ".join(f"`{tool}`" for tool in examples[:2])
    return f"Start with {quoted} before testing a more complex command."


def render_skill_md(allowlist: list[str]) -> str:
    allowlist_text = render_allowlist(allowlist)
    allowlist_v2_text = render_v2_allowlist(BROKER_CFG_V2["allowlist"])
    example_tools_text = render_example_tools(allowlist)
    return f"""---
name: {SKILL_NAME}
description: {SKILL_DESCRIPTION}
---

<!-- Generated by scripts/generate_skill.py. Do not edit SKILL.md by hand. -->

# Brokered CLI Troubleshooting

Use this skill when you expected ordinary local CLI behavior but have signs that command execution is being brokered.

The core mental model: this repo can make some tools look locally available even though they cross a broker boundary. The command actually runs in a separate broker process under a fixed allowlist. It is not a full local-process replacement.

Version matters:

- v1 preserves `argv`, `cwd`, stdout, stderr, and exit code, but captures stdout and stderr as a one-shot terminal result, does not transport stdin, and does not preserve interactive terminal semantics.
- v2 preserves `argv`, `cwd`, and exit status, streams stdin/stdout/stderr incrementally, forwards signals through the broker, and uses heartbeats for long-lived silent requests. It still does not promise PTY-like interactivity or local shell semantics.

## When to use this skill

Use it when a tool message or repo instruction explicitly points you here.

## First sanity check: is the tool even allowlisted?

{allowlist_text}

{allowlist_v2_text}

Before investigating session state, transport, or interactivity, compare the exact requested tool name against that list.

If the command you are debugging is outside that set, a normal session usually will not expose it through a generated shim at all. Expect `NOT_ALLOWED` or exit code `126` only if something still routes that tool name through the broker, such as a direct `cli/shim_cli.py --tool ...` call or a misleading shim name.

If the command is inside that set, continue with the checks below.

## First question: is this command brokered?

Do not assume a command is running as a normal local process just because you invoked it by name.

Strong clues that this repo's shim is in the path:

- `BROKER_SESSION_DIR` is set
- `command -v <tool>` resolves inside `"$BROKER_SESSION_DIR/bin"`
- `PATH` contains a session-local `bin/` directory under `BROKER_SESSION_DIR`
- errors mention `BROKER_UNAVAILABLE`, `BAD_RESPONSE`, `NOT_ALLOWED`, or session files
- failures reference `req.fifo`, `resp.fifo`, `client.lock`, or a broker session directory
- the session shim directory only contains allowlisted executable names

Run these checks before blaming the tool itself:

1. `echo "$BROKER_SESSION_DIR"`
2. `echo "$PATH"`
3. `command -v <tool>`
4. `ls -l "$BROKER_SESSION_DIR/bin" "$BROKER_SESSION_DIR" 2>/dev/null`

If those checks point at a session directory or generated shim symlinks, switch to the brokered execution mental model for the rest of the investigation.

## What the shim actually preserves

These parts are intentionally forwarded:

- tool name
- argument vector
- current working directory
- timeout
- raw stdout bytes
- raw stderr bytes
- exit code
- in v2, signal forwarding and incremental stdio transport

These parts do not behave like a normal local shell execution:

- stdin is not transported in v1
- v2 transports stdin, but still does not become a PTY
- interactive signal behavior is not preserved
- shell aliases, functions, and shell builtins are not forwarded
- only allowlisted executable names are available
- execution happens in the broker process, not in the caller's shell process
- environment forwarding is limited to explicit `env_delta` fields in protocol calls

## Fast triage once brokering is suspected

Check these in order:

1. Confirm the session exists.
   `echo "$BROKER_SESSION_DIR"`

2. Confirm the session files still exist.
   `ls -l "$BROKER_SESSION_DIR"`
   Expected entries: `req.fifo`, `resp.fifo`, `client.lock`, `bin/`, `logs/`

3. Confirm whether the tool is being invoked through the generated shim bin directory.
   `echo "$PATH"`
   `ls -l "$BROKER_SESSION_DIR/bin"`
   `command -v <tool>`

4. Confirm the tool name is allowlisted by the broker.
   The current repo config is in `agent_broker_v1/config.py`, unless `agent_broker_v1/config_local.py` is present.

5. Reproduce with direct shim invocation to remove PATH and symlink ambiguity.
   `BROKER_SESSION_DIR=... python3 cli/shim_cli.py --tool <tool> -- <args>`
   For v2, use:
   `BROKER_SESSION_DIR=... python3 cli/shim_cli_v2.py --tool <tool> -- <args>`

6. Inspect broker log artifacts for the matching request under `"$BROKER_SESSION_DIR/logs"`.

If step 3 shows an ordinary system path instead of the session `bin/`, this skill may not apply.

## Common failure classes

### `BROKER_UNAVAILABLE` or exit code `69`

Likely causes:

- `BROKER_SESSION_DIR` is unset
- the broker already shut down and cleaned up IPC files
- `req.fifo`, `resp.fifo`, or `client.lock` is missing
- the broker closed the response FIFO before replying
- the v2 broker heartbeat lease expired

What to do:

- verify `BROKER_SESSION_DIR`
- list the session directory contents
- restart or reattach to the broker session
- avoid assuming the session remains valid after broker shutdown

### `NOT_ALLOWED` or exit code `126`

This usually means something routed a non-allowlisted tool name through the broker.

In a normal session, commands outside the allowlist usually do not get generated shim symlinks in the first place.

Common causes:

- you called `cli/shim_cli.py` directly with `--tool <name>` for a tool that is not allowlisted
- the symlink name is different from the actual allowlisted command name
- the command is a shell builtin, alias, or function rather than an executable
- you expected a host tool to be brokered even though it is not in `BROKER_CFG_V1["allowlist"]`

What to do:

- inspect `agent_broker_v1/config.py` and `agent_broker_v1/config_local.py`
- confirm the exact invoked filename with `command -v <tool>`
- if testing `cli/shim_cli.py` directly, always pass `--tool`

### `TOOL_NOT_FOUND` or exit code `127`

The broker accepted the tool name, but its resolved executable was missing when the broker was configured.

What to do:

- inspect the broker startup output for the effective allowlist
- verify the executable exists on the host where the broker runs
- remember the allowlist is resolved with `shutil.which()` during broker startup

### `TIMEOUT` or exit code `124`

The broker uses `subprocess.run(..., timeout=...)`.

Implications:

- long-running commands need a larger timeout
- interactive waiting on stdin will often time out because stdin is not forwarded

What to do:

- retry with a larger timeout in direct mode:
  `python3 cli/shim_cli.py --tool <tool> --timeout-ms 120000 -- <args>`
- if the tool expects stdin, redesign the invocation to use files or explicit arguments instead

For v2, timeout policy is client-side and the direct CLI defaults to no timeout. If a timeout is explicitly enabled, a timed-out shim may send one or more forwarded signals and then report the observed terminal result from the child.

### `BAD_RESPONSE`, `BAD_JSON`, or exit code `70`

This strongly suggests a broker transport or protocol problem, not a problem in the target tool itself.

Likely causes:

- malformed FIFO traffic
- an unexpected response frame
- corrupt base64 payloads
- protocol mismatch

What to do:

- suspect shim or broker transport before blaming the tool
- reproduce with the simplest possible tool, such as `echo`
- inspect recent request log files in `logs/`
- if one request was interrupted mid-frame, retry a fresh request; the broker is designed to recover from abandoned partial requests

## Behaviors that are surprising but expected

These are not bugs by themselves:

- binary stdout and stderr are preserved as raw bytes
- large outputs may arrive over multiple transport chunks but still form one logical response
- stale responses with a different request id are ignored by the shim
- stale error frames with `id: null` are ignored by the shim while waiting for the active request
- the shim serializes client requests with a blocking `flock` on `client.lock`
- in v2, stdout and stderr may appear incrementally before the child exits
- in v2, forwarded signals describe broker intent, but terminal stop status reflects the observed child outcome

If output looks stale, check whether you are reading old log files rather than the current request result.

## Good debugging pattern

When behavior is unclear, reduce variables in this order:

1. Reproduce with direct shim invocation.
   `BROKER_SESSION_DIR=... python3 cli/shim_cli.py --tool echo -- hello`

2. Reproduce with a simple allowlisted executable.
   {example_tools_text}

3. Compare with an unshimmed local run of the same executable and arguments.
   If they differ, focus on broker/session/environment differences.

4. Inspect logs under `"$BROKER_SESSION_DIR/logs"`.
   The broker writes one stdout log and one stderr log per request id.

5. Check whether the command depends on unsupported features.
   Common examples: stdin input, TTY detection, prompts, job control, signal-driven interactivity.

If you cannot confirm brokering from the environment or path checks above, treat this skill as a hypothesis to test rather than an established fact.

## Constraints to remember before proposing fixes

- do not assume commands are local just because they were invoked by bare tool name
- do not describe brokered execution as identical to a normal local shell command
- do not assume shell builtins are available through the broker
- do not assume environment changes in the current shell are forwarded automatically
- do not assume the session directory survives broker shutdown
- do not treat transport errors as tool errors

## Recommended wording in agent responses

When reporting findings, be explicit about the execution boundary. Prefer wording like:

- "The command was invoked through the broker shim, so the executable ran in the broker process, not in the local shell."
- "This failure is consistent with broker session state or allowlist configuration, not with the tool itself."
- "The command expects stdin or interactivity, which this shim does not currently transport."

## Repo-specific references

- `README.md` for architecture and manual usage
- `cli/shim_cli.py` for direct debug entrypoint behavior
- `agent_broker_v1/shim.py` for client-side transport and response filtering
- `agent_broker_v1/broker.py` for allowlist enforcement, subprocess execution, timeout handling, and per-request logs
- `agent_broker_v1/config.py` and optional `agent_broker_v1/config_local.py` for the configured allowlist
- `tests/test_shim_cli.py` for concrete edge cases the current implementation intentionally handles
"""

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Generate SKILL.md from broker config.")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if SKILL.md does not match generated output.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=OUTPUT_PATH,
        help="Write the generated skill to this path.",
    )
    args = parser.parse_args(argv)

    allowlist = list(BROKER_CFG_V1.get("allowlist", []))
    rendered = render_skill_md(allowlist)

    if args.check:
        existing = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if existing != rendered:
            diff = difflib.unified_diff(
                existing.splitlines(),
                rendered.splitlines(),
                fromfile=str(args.output),
                tofile="generated",
                lineterm="",
            )
            sys.stderr.write("\n".join(diff) + "\n")
            return 1
        return 0

    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
